services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "subscribes"
      POSTGRES_USER: "subscriber"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./cmd/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
