// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

// Defines values for ApiErrorCode.
const (
	BadRequest       ApiErrorCode = "bad_request"
	Forbidden        ApiErrorCode = "forbidden"
	Internal         ApiErrorCode = "internal"
	MethodNotAllowed ApiErrorCode = "method_not_allowed"
	NotAcceptable    ApiErrorCode = "not_acceptable"
	NotFound         ApiErrorCode = "not_found"
	NotImplemented   ApiErrorCode = "not_implemented"
	RequestCancelled ApiErrorCode = "request_cancelled"
	RequestTimeout   ApiErrorCode = "request_timeout"
	StateConflict    ApiErrorCode = "state_conflict"
	Unauthorized     ApiErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ApiErrorCode enum.
func (e ApiErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case MethodNotAllowed:
		return true
	case NotAcceptable:
		return true
	case NotFound:
		return true
	case NotImplemented:
		return true
	case RequestCancelled:
		return true
	case RequestTimeout:
		return true
	case StateConflict:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// ApiError Описание ошибки
type ApiError struct {
	Error BaseError `json:"error"`
}

// ApiErrorCode defines model for ApiErrorCode.
type ApiErrorCode string

// ApiErrorParams Параметры ошибки
type ApiErrorParams struct {
	// AdditionalInfo Дополнительная информация о ошибке
	AdditionalInfo *[]string `json:"additional_info,omitempty"`

	// Validations Информации о валидации полей
	Validations *[]ValidationInfo `json:"validations,omitempty"`
}

// BaseError defines model for BaseError.
type BaseError struct {
	Code ApiErrorCode `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`

	// Params Параметры ошибки
	Params *ApiErrorParams `json:"params,omitempty"`
}

// ValidationInfo Информация о валидации поля
type ValidationInfo struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ApiErrorResponse Описание ошибки
type ApiErrorResponse = ApiError
