// Package subscribe provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package subscribe

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "subscribes/openapi"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// SubscribeInInfo defines model for SubscribeInInfo.
type SubscribeInInfo struct {
	// EndDate Дата окончания действия подписки в формате ММ-ГГГГ.Если не задана, то рассчитывается на основании даты начала подписки плюс месяц
	EndDate *string `json:"end_date,omitempty"`

	// Price Стоимость подписки
	Price int `json:"price"`

	// ServiceName Наименование сервиса
	ServiceName string `json:"service_name"`

	// StartDate Дата начала действия подписки в формате ММ-ГГГГ
	StartDate string `json:"start_date"`

	// UserId Идентификатор пользователя
	UserId openapi_types.UUID `json:"user_id"`
}

// SubscribeOuInfo defines model for SubscribeOuInfo.
type SubscribeOuInfo struct {
	// EndDate Дата окончания действия подписки в формате ММ-ГГГГ
	EndDate *string `json:"end_date,omitempty"`

	// Id Идентификатор подписки
	Id openapi_types.UUID `json:"id"`

	// Price Стоимость подписки
	Price int `json:"price"`

	// ServiceName Наименование сервиса
	ServiceName string `json:"service_name"`

	// StartDate Дата начала действия подписки в формате ММ-ГГГГ
	StartDate string `json:"start_date"`

	// UserId Идентификатор пользователя
	UserId openapi_types.UUID `json:"user_id"`
}

// SubscribePricesStat defines model for SubscribePricesStat.
type SubscribePricesStat struct {
	TotalPrice int `json:"total_price"`
}

// PageNumber defines model for PageNumber.
type PageNumber = int

// PageSize defines model for PageSize.
type PageSize = int

// GetSubscribeResponse defines model for GetSubscribeResponse.
type GetSubscribeResponse = SubscribeOuInfo

// GetSubscribesPriceStat defines model for GetSubscribesPriceStat.
type GetSubscribesPriceStat = SubscribePricesStat

// CreateSubscribeRequest defines model for CreateSubscribeRequest.
type CreateSubscribeRequest = SubscribeInInfo

// UpdateSubscribeRequest defines model for UpdateSubscribeRequest.
type UpdateSubscribeRequest = SubscribeInInfo

// GetSubscribesListParams defines parameters for GetSubscribesList.
type GetSubscribesListParams struct {
	PageNumber *PageNumber `form:"pageNumber,omitempty" json:"pageNumber,omitempty"`
	PageSize   *PageSize   `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetCalcedSubscribesParams defines parameters for GetCalcedSubscribes.
type GetCalcedSubscribesParams struct {
	// StartDate Дата начала периода отбора подписок
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Дата окончания периода отбора подписок
	EndDate *string `form:"end_date,omitempty" json:"end_date,omitempty"`

	// UserId Идентификатор пользователя для отбора подписок
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ServiceName Наименование сервиса
	ServiceName *string `form:"service_name,omitempty" json:"service_name,omitempty"`
}

// UpdateSubscribeJSONRequestBody defines body for UpdateSubscribe for application/json ContentType.
type UpdateSubscribeJSONRequestBody = SubscribeInInfo

// CreateSubscribeJSONRequestBody defines body for CreateSubscribe for application/json ContentType.
type CreateSubscribeJSONRequestBody = SubscribeInInfo

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete Subscribe information per ID
	// (DELETE /subscribe/{id})
	DeleteSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Retrieves specific Subscribe
	// (GET /subscribe/{id})
	GetSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update Subscribe information per ID
	// (PUT /subscribe/{id})
	UpdateSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Retrieve a list of Subscribes
	// (GET /subscribes)
	GetSubscribesList(w http.ResponseWriter, r *http.Request, params GetSubscribesListParams)
	// Creates the Subscribe
	// (POST /subscribes)
	CreateSubscribe(w http.ResponseWriter, r *http.Request)
	// Calc summary specific Subscribes
	// (GET /subscribes/calc)
	GetCalcedSubscribes(w http.ResponseWriter, r *http.Request, params GetCalcedSubscribesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Delete Subscribe information per ID
// (DELETE /subscribe/{id})
func (_ Unimplemented) DeleteSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieves specific Subscribe
// (GET /subscribe/{id})
func (_ Unimplemented) GetSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Subscribe information per ID
// (PUT /subscribe/{id})
func (_ Unimplemented) UpdateSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a list of Subscribes
// (GET /subscribes)
func (_ Unimplemented) GetSubscribesList(w http.ResponseWriter, r *http.Request, params GetSubscribesListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Creates the Subscribe
// (POST /subscribes)
func (_ Unimplemented) CreateSubscribe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Calc summary specific Subscribes
// (GET /subscribes/calc)
func (_ Unimplemented) GetCalcedSubscribes(w http.ResponseWriter, r *http.Request, params GetCalcedSubscribesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteSubscribe operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubscribe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSubscribe(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscribe operation middleware
func (siw *ServerInterfaceWrapper) GetSubscribe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscribe(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSubscribe operation middleware
func (siw *ServerInterfaceWrapper) UpdateSubscribe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSubscribe(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscribesList operation middleware
func (siw *ServerInterfaceWrapper) GetSubscribesList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubscribesListParams

	// ------------- Optional query parameter "pageNumber" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageNumber", r.URL.Query(), &params.PageNumber, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageNumber", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscribesList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubscribe operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscribe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscribe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalcedSubscribes operation middleware
func (siw *ServerInterfaceWrapper) GetCalcedSubscribes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCalcedSubscribesParams

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start_date", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_date", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "service_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "service_name", r.URL.Query(), &params.ServiceName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalcedSubscribes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/subscribe/{id}", wrapper.DeleteSubscribe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscribe/{id}", wrapper.GetSubscribe)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/subscribe/{id}", wrapper.UpdateSubscribe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscribes", wrapper.GetSubscribesList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subscribes", wrapper.CreateSubscribe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscribes/calc", wrapper.GetCalcedSubscribes)
	})

	return r
}

type GetSubscribeResponseJSONResponse SubscribeOuInfo

type GetSubscribesPriceStatJSONResponse SubscribePricesStat

type DeleteSubscribeRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteSubscribeResponseObject interface {
	VisitDeleteSubscribeResponse(w http.ResponseWriter) error
}

type DeleteSubscribe204Response struct {
}

func (response DeleteSubscribe204Response) VisitDeleteSubscribeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSubscribe400ApplicationProblemPlusJSONResponse struct{ externalRef0.ApiErrorResponse }

func (response DeleteSubscribe400ApplicationProblemPlusJSONResponse) VisitDeleteSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSubscribe404ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response DeleteSubscribe404ApplicationProblemPlusJSONResponse) VisitDeleteSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSubscribe500ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response DeleteSubscribe500ApplicationProblemPlusJSONResponse) VisitDeleteSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSubscribedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response DeleteSubscribedefaultApplicationProblemPlusJSONResponse) VisitDeleteSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSubscribeRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSubscribeResponseObject interface {
	VisitGetSubscribeResponse(w http.ResponseWriter) error
}

type GetSubscribe200JSONResponse struct {
	GetSubscribeResponseJSONResponse
}

func (response GetSubscribe200JSONResponse) VisitGetSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribe400ApplicationProblemPlusJSONResponse struct{ externalRef0.ApiErrorResponse }

func (response GetSubscribe400ApplicationProblemPlusJSONResponse) VisitGetSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribe404ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response GetSubscribe404ApplicationProblemPlusJSONResponse) VisitGetSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribe500ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response GetSubscribe500ApplicationProblemPlusJSONResponse) VisitGetSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetSubscribedefaultApplicationProblemPlusJSONResponse) VisitGetSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateSubscribeRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateSubscribeJSONRequestBody
}

type UpdateSubscribeResponseObject interface {
	VisitUpdateSubscribeResponse(w http.ResponseWriter) error
}

type UpdateSubscribe200JSONResponse struct {
	GetSubscribeResponseJSONResponse
}

func (response UpdateSubscribe200JSONResponse) VisitUpdateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscribe400ApplicationProblemPlusJSONResponse struct{ externalRef0.ApiErrorResponse }

func (response UpdateSubscribe400ApplicationProblemPlusJSONResponse) VisitUpdateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscribe404ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response UpdateSubscribe404ApplicationProblemPlusJSONResponse) VisitUpdateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscribe500ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response UpdateSubscribe500ApplicationProblemPlusJSONResponse) VisitUpdateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscribedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response UpdateSubscribedefaultApplicationProblemPlusJSONResponse) VisitUpdateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSubscribesListRequestObject struct {
	Params GetSubscribesListParams
}

type GetSubscribesListResponseObject interface {
	VisitGetSubscribesListResponse(w http.ResponseWriter) error
}

type GetSubscribesList200JSONResponse []SubscribeOuInfo

func (response GetSubscribesList200JSONResponse) VisitGetSubscribesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribesList400ApplicationProblemPlusJSONResponse struct{ externalRef0.ApiErrorResponse }

func (response GetSubscribesList400ApplicationProblemPlusJSONResponse) VisitGetSubscribesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribesList500ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response GetSubscribesList500ApplicationProblemPlusJSONResponse) VisitGetSubscribesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscribesListdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetSubscribesListdefaultApplicationProblemPlusJSONResponse) VisitGetSubscribesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSubscribeRequestObject struct {
	Body *CreateSubscribeJSONRequestBody
}

type CreateSubscribeResponseObject interface {
	VisitCreateSubscribeResponse(w http.ResponseWriter) error
}

type CreateSubscribe201JSONResponse struct {
	GetSubscribeResponseJSONResponse
}

func (response CreateSubscribe201JSONResponse) VisitCreateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscribe400ApplicationProblemPlusJSONResponse struct{ externalRef0.ApiErrorResponse }

func (response CreateSubscribe400ApplicationProblemPlusJSONResponse) VisitCreateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscribe409ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response CreateSubscribe409ApplicationProblemPlusJSONResponse) VisitCreateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscribe500ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response CreateSubscribe500ApplicationProblemPlusJSONResponse) VisitCreateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscribedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response CreateSubscribedefaultApplicationProblemPlusJSONResponse) VisitCreateSubscribeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetCalcedSubscribesRequestObject struct {
	Params GetCalcedSubscribesParams
}

type GetCalcedSubscribesResponseObject interface {
	VisitGetCalcedSubscribesResponse(w http.ResponseWriter) error
}

type GetCalcedSubscribes200JSONResponse struct {
	GetSubscribesPriceStatJSONResponse
}

func (response GetCalcedSubscribes200JSONResponse) VisitGetCalcedSubscribesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCalcedSubscribes400ApplicationProblemPlusJSONResponse struct{ externalRef0.ApiErrorResponse }

func (response GetCalcedSubscribes400ApplicationProblemPlusJSONResponse) VisitGetCalcedSubscribesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCalcedSubscribes404ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response GetCalcedSubscribes404ApplicationProblemPlusJSONResponse) VisitGetCalcedSubscribesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCalcedSubscribes500ApplicationProblemPlusJSONResponse externalRef0.ApiError

func (response GetCalcedSubscribes500ApplicationProblemPlusJSONResponse) VisitGetCalcedSubscribesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCalcedSubscribesdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetCalcedSubscribesdefaultApplicationProblemPlusJSONResponse) VisitGetCalcedSubscribesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delete Subscribe information per ID
	// (DELETE /subscribe/{id})
	DeleteSubscribe(ctx context.Context, request DeleteSubscribeRequestObject) (DeleteSubscribeResponseObject, error)
	// Retrieves specific Subscribe
	// (GET /subscribe/{id})
	GetSubscribe(ctx context.Context, request GetSubscribeRequestObject) (GetSubscribeResponseObject, error)
	// Update Subscribe information per ID
	// (PUT /subscribe/{id})
	UpdateSubscribe(ctx context.Context, request UpdateSubscribeRequestObject) (UpdateSubscribeResponseObject, error)
	// Retrieve a list of Subscribes
	// (GET /subscribes)
	GetSubscribesList(ctx context.Context, request GetSubscribesListRequestObject) (GetSubscribesListResponseObject, error)
	// Creates the Subscribe
	// (POST /subscribes)
	CreateSubscribe(ctx context.Context, request CreateSubscribeRequestObject) (CreateSubscribeResponseObject, error)
	// Calc summary specific Subscribes
	// (GET /subscribes/calc)
	GetCalcedSubscribes(ctx context.Context, request GetCalcedSubscribesRequestObject) (GetCalcedSubscribesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteSubscribe operation middleware
func (sh *strictHandler) DeleteSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteSubscribeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSubscribe(ctx, request.(DeleteSubscribeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSubscribe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSubscribeResponseObject); ok {
		if err := validResponse.VisitDeleteSubscribeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscribe operation middleware
func (sh *strictHandler) GetSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetSubscribeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscribe(ctx, request.(GetSubscribeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscribe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscribeResponseObject); ok {
		if err := validResponse.VisitGetSubscribeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSubscribe operation middleware
func (sh *strictHandler) UpdateSubscribe(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateSubscribeRequestObject

	request.Id = id

	var body UpdateSubscribeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSubscribe(ctx, request.(UpdateSubscribeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSubscribe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSubscribeResponseObject); ok {
		if err := validResponse.VisitUpdateSubscribeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscribesList operation middleware
func (sh *strictHandler) GetSubscribesList(w http.ResponseWriter, r *http.Request, params GetSubscribesListParams) {
	var request GetSubscribesListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscribesList(ctx, request.(GetSubscribesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscribesList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscribesListResponseObject); ok {
		if err := validResponse.VisitGetSubscribesListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSubscribe operation middleware
func (sh *strictHandler) CreateSubscribe(w http.ResponseWriter, r *http.Request) {
	var request CreateSubscribeRequestObject

	var body CreateSubscribeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscribe(ctx, request.(CreateSubscribeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscribe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubscribeResponseObject); ok {
		if err := validResponse.VisitCreateSubscribeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCalcedSubscribes operation middleware
func (sh *strictHandler) GetCalcedSubscribes(w http.ResponseWriter, r *http.Request, params GetCalcedSubscribesParams) {
	var request GetCalcedSubscribesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCalcedSubscribes(ctx, request.(GetCalcedSubscribesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCalcedSubscribes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCalcedSubscribesResponseObject); ok {
		if err := validResponse.VisitGetCalcedSubscribesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
